//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.UMS.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPI.UMS.BLL.Resources.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Bool_Text_No {
            get {
                return ResourceManager.GetString("Bool_Text_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Bool_Text_Yes {
            get {
                return ResourceManager.GetString("Bool_Text_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        internal static string DateTime_Text_Expired {
            get {
                return ResourceManager.GetString("DateTime_Text_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string DateTime_Text_Never {
            get {
                return ResourceManager.GetString("DateTime_Text_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The First Name cannot be blank or empty.
        /// </summary>
        internal static string Info_FirstName_Null {
            get {
                return ResourceManager.GetString("Info_FirstName_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last Name cannot be blank or empty.
        /// </summary>
        internal static string Info_LastName_Null {
            get {
                return ResourceManager.GetString("Info_LastName_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password entered does not match either the complexity, length or history requirements.  Please try again..
        /// </summary>
        internal static string Password_Change_Invalid_Complexity {
            get {
                return ResourceManager.GetString("Password_Change_Invalid_Complexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password did not match the confirmation.  Please go back and try again..
        /// </summary>
        internal static string Password_Change_Invalid_NoConfirm {
            get {
                return ResourceManager.GetString("Password_Change_Invalid_NoConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, your password will not expire for a while..
        /// </summary>
        internal static string Password_Expires_Future {
            get {
                return ResourceManager.GetString("Password_Expires_Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, your password will never expire..
        /// </summary>
        internal static string Password_Expires_Never {
            get {
                return ResourceManager.GetString("Password_Expires_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, your password will expire next month..
        /// </summary>
        internal static string Password_Expires_NextMonth {
            get {
                return ResourceManager.GetString("Password_Expires_NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, your password will expire this month..
        /// </summary>
        internal static string Password_Expires_ThisMonth {
            get {
                return ResourceManager.GetString("Password_Expires_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, your password will expire &lt;span style=&quot;color:red;&quot;&gt;today!&lt;/span&gt;.
        /// </summary>
        internal static string Password_Expires_Today {
            get {
                return ResourceManager.GetString("Password_Expires_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, your password will expire &lt;span style=&quot;color:red;&quot;&gt;tomorrow!&lt;/span&gt;.
        /// </summary>
        internal static string Password_Expires_Tomorrow {
            get {
                return ResourceManager.GetString("Password_Expires_Tomorrow", resourceCulture);
            }
        }
    }
}
