//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Admin", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///            &lt;span style=&quot;font-weight: bold; color: red;&quot;&gt;STOP! READ THIS FIRST!&lt;/span&gt;
        ///            &lt;br /&gt;
        ///            Ensure you understand the specifics below before using the Application Reset functionality.
        ///            It could cause potential loss of information and settings.
        ///        &lt;/p&gt;
        ///        &lt;p&gt;
        ///            &lt;strong&gt;What Should I Know?&lt;/strong&gt;
        ///            &lt;br /&gt;
        ///            The application reset function was designed primarily for developers and system
        ///            administrators that  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config_AppReset_Body {
            get {
                return ResourceManager.GetString("Config_AppReset_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return confirm(&apos;Last chance to say no! This action also decrypts the membership section after it is cleared.\r\n\r\nAre you sure you want to reset the application?&apos;);.
        /// </summary>
        internal static string Config_AppReset_Conf {
            get {
                return ResourceManager.GetString("Config_AppReset_Conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Database?.
        /// </summary>
        internal static string Config_AppReset_RemoveDatabase {
            get {
                return ResourceManager.GetString("Config_AppReset_RemoveDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Application.
        /// </summary>
        internal static string Config_AppReset_SubmitText {
            get {
                return ResourceManager.GetString("Config_AppReset_SubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This timeline only shows configuration and system-wide changes.  It does not reflect any administrative or user changes, however it does work the same way as the main system timeline..
        /// </summary>
        internal static string Config_Dash_Dialog_Message {
            get {
                return ResourceManager.GetString("Config_Dash_Dialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Configuration Timeline.
        /// </summary>
        internal static string Config_Dash_Dialog_Title {
            get {
                return ResourceManager.GetString("Config_Dash_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re timeline is currently empty.  Don&apos;t worry nothing is really wrong, the system just has not logged any messages worth showing yet.  Remember this timeline is only for System Messages, all other messages will show up in the main Administration timeline..
        /// </summary>
        internal static string Config_Dash_Empty_Message {
            get {
                return ResourceManager.GetString("Config_Dash_Empty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Timeline Exists!.
        /// </summary>
        internal static string Config_Dash_Empty_Title {
            get {
                return ResourceManager.GetString("Config_Dash_Empty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Database Configuration.
        /// </summary>
        internal static string Config_Dash_Links_DB {
            get {
                return ResourceManager.GetString("Config_Dash_Links_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset uManage.
        /// </summary>
        internal static string Config_Dash_Links_Reset {
            get {
                return ResourceManager.GetString("Config_Dash_Links_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update SMTP Settings.
        /// </summary>
        internal static string Config_Dash_Links_SMTP {
            get {
                return ResourceManager.GetString("Config_Dash_Links_SMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links.
        /// </summary>
        internal static string Config_Dash_Links_Title {
            get {
                return ResourceManager.GetString("Config_Dash_Links_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Count:.
        /// </summary>
        internal static string Config_Dash_SQL_ConnCount {
            get {
                return ResourceManager.GetString("Config_Dash_SQL_ConnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent CPU Time:.
        /// </summary>
        internal static string Config_Dash_SQL_CPUPercent {
            get {
                return ResourceManager.GetString("Config_Dash_SQL_CPUPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent IO Time:.
        /// </summary>
        internal static string Config_Dash_SQL_IOPercent {
            get {
                return ResourceManager.GetString("Config_Dash_SQL_IOPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Reads/Sec:.
        /// </summary>
        internal static string Config_Dash_SQL_IORead {
            get {
                return ResourceManager.GetString("Config_Dash_SQL_IORead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Writes/Sec:.
        /// </summary>
        internal static string Config_Dash_SQL_IOWrite {
            get {
                return ResourceManager.GetString("Config_Dash_SQL_IOWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics Could Not Be Found!.
        /// </summary>
        internal static string Config_Dash_SQL_NotFound {
            get {
                return ResourceManager.GetString("Config_Dash_SQL_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet Errors:.
        /// </summary>
        internal static string Config_Dash_SQL_PacketErr {
            get {
                return ResourceManager.GetString("Config_Dash_SQL_PacketErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packets Received:.
        /// </summary>
        internal static string Config_Dash_SQL_PacketRec {
            get {
                return ResourceManager.GetString("Config_Dash_SQL_PacketRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packets Sent:.
        /// </summary>
        internal static string Config_Dash_SQL_PacketSent {
            get {
                return ResourceManager.GetString("Config_Dash_SQL_PacketSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLServer Statistics.
        /// </summary>
        internal static string Config_Dash_SQL_Title {
            get {
                return ResourceManager.GetString("Config_Dash_SQL_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need your help to better define what would be useful in this dashboard. Please
        ///                            submit comments and feedback at CodePlex using either the Discussion board or the
        ///                            Issue Tracking tools.
        ///                            &lt;br /&gt;
        ///                            &lt;br /&gt;
        ///                            &lt;a href=&quot;http://umanage.codeplex.com&quot; target=&quot;_blank&quot;&gt;http://umanage.codeplex.com&lt;/a&gt;.
        /// </summary>
        internal static string Config_Dash_Suggestions_Body {
            get {
                return ResourceManager.GetString("Config_Dash_Suggestions_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Suggestions!.
        /// </summary>
        internal static string Config_Dash_Suggestions_Title {
            get {
                return ResourceManager.GetString("Config_Dash_Suggestions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///            Due to the possibility of the application failing to run when SQL changes are made
        ///            the current configuration can only be viewed, it cannot be modified from within
        ///            the application. To make changes to the configuration use either IIS&apos; Management
        ///            Snap-In or Reset the application to re-create the database.
        ///        &lt;/p&gt;.
        /// </summary>
        internal static string Config_Database_Body {
            get {
                return ResourceManager.GetString("Config_Database_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database / Catalog:.
        /// </summary>
        internal static string Config_Database_Catalog {
            get {
                return ResourceManager.GetString("Config_Database_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Server:.
        /// </summary>
        internal static string Config_Database_Server {
            get {
                return ResourceManager.GetString("Config_Database_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Config_Database_Username {
            get {
                return ResourceManager.GetString("Config_Database_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot edit the domain name once the system is up and running.  Use the application reset instead..
        /// </summary>
        internal static string Config_Domain_FQDNNoEdit {
            get {
                return ResourceManager.GetString("Config_Domain_FQDNNoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you click save the system will first attempt to validate the credentials supplied before saving them..
        /// </summary>
        internal static string Config_Domain_Notice {
            get {
                return ResourceManager.GetString("Config_Domain_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string Config_Domain_SubmitText {
            get {
                return ResourceManager.GetString("Config_Domain_SubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return confirm(&apos;Changing the user credentials used to connect to the domain could cause problems or fail in future requests causing users and administrators unable to access the application.  In addition updating the configuration will cause the application to recycle which could cause in session users to experience a time-out or loose their work.\r\n\r\nAre you sure you want to continue?&apos;);.
        /// </summary>
        internal static string Config_Domain_Submit_Conf {
            get {
                return ResourceManager.GetString("Config_Domain_Submit_Conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain settings were tested and applied successfully.  uManage verified the credentials supplied using &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        internal static string Config_Domain_Success_Message {
            get {
                return ResourceManager.GetString("Config_Domain_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Changes Applied Successfully.
        /// </summary>
        internal static string Config_Domain_Success_Title {
            get {
                return ResourceManager.GetString("Config_Domain_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Address:.
        /// </summary>
        internal static string Config_NewUser_Address {
            get {
                return ResourceManager.GetString("Config_NewUser_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enable user creation before you can modify any settings. If you leave user
        ///        creation turned off uManage will not allow Admin users to create new user accounts,
        ///        they will all need to be created manually..
        /// </summary>
        internal static string Config_NewUser_Body {
            get {
                return ResourceManager.GetString("Config_NewUser_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company City:.
        /// </summary>
        internal static string Config_NewUser_City {
            get {
                return ResourceManager.GetString("Config_NewUser_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Defaults.
        /// </summary>
        internal static string Config_NewUser_Company {
            get {
                return ResourceManager.GetString("Config_NewUser_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Container.
        /// </summary>
        internal static string Config_NewUser_Container {
            get {
                return ResourceManager.GetString("Config_NewUser_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Country:.
        /// </summary>
        internal static string Config_NewUser_Country {
            get {
                return ResourceManager.GetString("Config_NewUser_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinguished Name:.
        /// </summary>
        internal static string Config_NewUser_DN {
            get {
                return ResourceManager.GetString("Config_NewUser_DN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: OU=MyUsers,DC=MyDomain,DC=com.
        /// </summary>
        internal static string Config_NewUser_DN_Instructions {
            get {
                return ResourceManager.GetString("Config_NewUser_DN_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable User Creation?.
        /// </summary>
        internal static string Config_NewUser_Enable {
            get {
                return ResourceManager.GetString("Config_NewUser_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username Format.
        /// </summary>
        internal static string Config_NewUser_Format {
            get {
                return ResourceManager.GetString("Config_NewUser_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $fi$ - First Initial
        ///                    &lt;br /&gt;
        ///                    $fname$ - First Name
        ///                    &lt;br /&gt;
        ///                    $mi$ - Middle Initial
        ///                    &lt;br /&gt;
        ///                    $mname$ - Middle Name
        ///                    &lt;br /&gt;
        ///                    $li$ - Last Initial
        ///                    &lt;br /&gt;
        ///                    $lname$ - Last Name.
        /// </summary>
        internal static string Config_NewUser_FormatStrings {
            get {
                return ResourceManager.GetString("Config_NewUser_FormatStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username Format String:.
        /// </summary>
        internal static string Config_NewUser_FormatTest {
            get {
                return ResourceManager.GetString("Config_NewUser_FormatTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test (John Michael Smith).
        /// </summary>
        internal static string Config_NewUser_FormatTest_Button {
            get {
                return ResourceManager.GetString("Config_NewUser_FormatTest_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Required Field Missing!&lt;/strong&gt;&lt;br /&gt;You must supply a default username format..
        /// </summary>
        internal static string Config_NewUser_FormatTest_Missing {
            get {
                return ResourceManager.GetString("Config_NewUser_FormatTest_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Characters:.
        /// </summary>
        internal static string Config_NewUser_FormatTitle {
            get {
                return ResourceManager.GetString("Config_NewUser_FormatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name:.
        /// </summary>
        internal static string Config_NewUser_Name {
            get {
                return ResourceManager.GetString("Config_NewUser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Phone:.
        /// </summary>
        internal static string Config_NewUser_Phone {
            get {
                return ResourceManager.GetString("Config_NewUser_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Postal Code:.
        /// </summary>
        internal static string Config_NewUser_Postal {
            get {
                return ResourceManager.GetString("Config_NewUser_Postal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Defaults.
        /// </summary>
        internal static string Config_NewUser_Save {
            get {
                return ResourceManager.GetString("Config_NewUser_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings could not be saved because of this error: {0}.
        /// </summary>
        internal static string Config_NewUser_Save_Fail_Msg {
            get {
                return ResourceManager.GetString("Config_NewUser_Save_Fail_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Save Settings!.
        /// </summary>
        internal static string Config_NewUser_Save_Fail_Title {
            get {
                return ResourceManager.GetString("Config_NewUser_Save_Fail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The defaults have been saved and will be used for all future user accounts..
        /// </summary>
        internal static string Config_NewUser_Save_Success_Msg {
            get {
                return ResourceManager.GetString("Config_NewUser_Save_Success_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Defaults!.
        /// </summary>
        internal static string Config_NewUser_Save_Success_Title {
            get {
                return ResourceManager.GetString("Config_NewUser_Save_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company State:.
        /// </summary>
        internal static string Config_NewUser_State {
            get {
                return ResourceManager.GetString("Config_NewUser_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Location.
        /// </summary>
        internal static string Config_OfficeLoc_Add {
            get {
                return ResourceManager.GetString("Config_OfficeLoc_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Location.
        /// </summary>
        internal static string Config_OfficeLoc_AddLoc {
            get {
                return ResourceManager.GetString("Config_OfficeLoc_AddLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///            Organizations have the option of enabling a drop down list for the Office location
        ///            field in Active Directory. By enabling this option you will force users to select
        ///            a predefined location when selecting their office. When disabled users can enter
        ///            their location into a free-form textbox.
        ///        &lt;/p&gt;.
        /// </summary>
        internal static string Config_OfficeLoc_Body {
            get {
                return ResourceManager.GetString("Config_OfficeLoc_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a location to edit....
        /// </summary>
        internal static string Config_OfficeLoc_DefaultDropDownText {
            get {
                return ResourceManager.GetString("Config_OfficeLoc_DefaultDropDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Locations.
        /// </summary>
        internal static string Config_OfficeLoc_EditLocs {
            get {
                return ResourceManager.GetString("Config_OfficeLoc_EditLocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Office Location List?.
        /// </summary>
        internal static string Config_OfficeLoc_Enable {
            get {
                return ResourceManager.GetString("Config_OfficeLoc_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the location because: .
        /// </summary>
        internal static string Config_OfficeLoc_Failure_Message {
            get {
                return ResourceManager.GetString("Config_OfficeLoc_Failure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Save the Location!.
        /// </summary>
        internal static string Config_OfficeLoc_Failure_Title {
            get {
                return ResourceManager.GetString("Config_OfficeLoc_Failure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name:.
        /// </summary>
        internal static string Config_OfficeLoc_Name {
            get {
                return ResourceManager.GetString("Config_OfficeLoc_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Location.
        /// </summary>
        internal static string Config_OfficeLoc_Save {
            get {
                return ResourceManager.GetString("Config_OfficeLoc_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select A Location:.
        /// </summary>
        internal static string Config_OfficeLoc_SelectLoc {
            get {
                return ResourceManager.GetString("Config_OfficeLoc_SelectLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved the location changes to the system..
        /// </summary>
        internal static string Config_OfficeLoc_Success_Message {
            get {
                return ResourceManager.GetString("Config_OfficeLoc_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Location!.
        /// </summary>
        internal static string Config_OfficeLoc_Success_Title {
            get {
                return ResourceManager.GetString("Config_OfficeLoc_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///            Use the settings below to configure how the user portal displays to the users.
        ///        &lt;/p&gt;.
        /// </summary>
        internal static string Config_Portal_Body {
            get {
                return ResourceManager.GetString("Config_Portal_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uManage was unable to save your configuration changes.  Please go back and try again..
        /// </summary>
        internal static string Config_Portal_Failure_Description {
            get {
                return ResourceManager.GetString("Config_Portal_Failure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Save Settings!.
        /// </summary>
        internal static string Config_Portal_Failure_Title {
            get {
                return ResourceManager.GetString("Config_Portal_Failure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Configuration.
        /// </summary>
        internal static string Config_Portal_SubmitText {
            get {
                return ResourceManager.GetString("Config_Portal_SubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return confirm(&apos;You are about to make changes to how the User Portal allows users to interact with the system.  It also may allow unwanted changes to your Active Directory database.  In addition updating the configuration will cause the application to recycle which could cause in session users to experience a time-out or loose their work.\r\n\r\nAre you sure you want to continue?&apos;);.
        /// </summary>
        internal static string Config_Portal_Submit_Conf {
            get {
                return ResourceManager.GetString("Config_Portal_Submit_Conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes were successfully saved to the configuration file and are now in effect..
        /// </summary>
        internal static string Config_Portal_Success_Description {
            get {
                return ResourceManager.GetString("Config_Portal_Success_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes Saved!.
        /// </summary>
        internal static string Config_Portal_Success_Title {
            get {
                return ResourceManager.GetString("Config_Portal_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Mode:.
        /// </summary>
        internal static string Config_SMTP_Auth_Title {
            get {
                return ResourceManager.GetString("Config_SMTP_Auth_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///            &lt;strong&gt;Why Use SMTP?&lt;/strong&gt;
        ///            &lt;br /&gt;
        ///            Simple actually; many of the features of uManage for communication between users,
        ///            administrators and even help desk technicians utilize the SMTP server to send notifications
        ///            or alerts to the user. While they are not vital to the system to run it is usually
        ///            easier to allow users to get an e-mail and then check the website thanks to the
        ///            links in the e-mail instead of periodicall [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config_SMTP_Body {
            get {
                return ResourceManager.GetString("Config_SMTP_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;The password verification did not match the original password.  Please ensure both password&apos;s match..
        /// </summary>
        internal static string Config_SMTP_ConfPass_NoCompare {
            get {
                return ResourceManager.GetString("Config_SMTP_ConfPass_NoCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;You must enter a password..
        /// </summary>
        internal static string Config_SMTP_ConfPass_Required {
            get {
                return ResourceManager.GetString("Config_SMTP_ConfPass_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Password:.
        /// </summary>
        internal static string Config_SMTP_ConfPass_Title {
            get {
                return ResourceManager.GetString("Config_SMTP_ConfPass_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uManage was either unable to test or save the settings.  Please check your selections and try again..
        /// </summary>
        internal static string Config_SMTP_Failure_Description {
            get {
                return ResourceManager.GetString("Config_SMTP_Failure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Configure Settings.
        /// </summary>
        internal static string Config_SMTP_Failure_Title {
            get {
                return ResourceManager.GetString("Config_SMTP_Failure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;You must enter a valid e-mail address..
        /// </summary>
        internal static string Config_SMTP_From_InValid {
            get {
                return ResourceManager.GetString("Config_SMTP_From_InValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;You must enter an e-mail address for the SMTP service to use..
        /// </summary>
        internal static string Config_SMTP_From_Required {
            get {
                return ResourceManager.GetString("Config_SMTP_From_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Address:.
        /// </summary>
        internal static string Config_SMTP_From_Title {
            get {
                return ResourceManager.GetString("Config_SMTP_From_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///            When you click save uManage will attempt to send a test e-mail message to the address
        ///            below before saving the settings.
        ///        &lt;/p&gt;.
        /// </summary>
        internal static string Config_SMTP_Notice {
            get {
                return ResourceManager.GetString("Config_SMTP_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;You must enter a password..
        /// </summary>
        internal static string Config_SMTP_Pass_Required {
            get {
                return ResourceManager.GetString("Config_SMTP_Pass_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Config_SMTP_Pass_Title {
            get {
                return ResourceManager.GetString("Config_SMTP_Pass_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;You must enter a valid TCP/IP Port to use..
        /// </summary>
        internal static string Config_SMTP_Port_Invalid {
            get {
                return ResourceManager.GetString("Config_SMTP_Port_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;You must enter a TCP/IP Port to use..
        /// </summary>
        internal static string Config_SMTP_Port_Required {
            get {
                return ResourceManager.GetString("Config_SMTP_Port_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string Config_SMTP_Port_Title {
            get {
                return ResourceManager.GetString("Config_SMTP_Port_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;You must enter a server URL to connect to..
        /// </summary>
        internal static string Config_SMTP_Server_Required {
            get {
                return ResourceManager.GetString("Config_SMTP_Server_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address:.
        /// </summary>
        internal static string Config_SMTP_Server_Title {
            get {
                return ResourceManager.GetString("Config_SMTP_Server_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SSL?.
        /// </summary>
        internal static string Config_SMTP_SSL_Title {
            get {
                return ResourceManager.GetString("Config_SMTP_SSL_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Configuration.
        /// </summary>
        internal static string Config_SMTP_SubmitText {
            get {
                return ResourceManager.GetString("Config_SMTP_SubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return confirm(&apos;You are about to make changes to the current SMTP server settings.  If the settings provided are not accurate it could cause notifications to fail to send.  In addition updating the configuration will cause the application to recycle which could cause in session users to experience a time-out or loose their work.\r\n\r\nAre you sure you want to continue?&apos;);.
        /// </summary>
        internal static string Config_SMTP_Submit_Conf {
            get {
                return ResourceManager.GetString("Config_SMTP_Submit_Conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SMTP settings were validated and properly saved to the configuration file.  uManage will now send e-mail notifications using the updated settings.  Please check the test account for a confirmation message..
        /// </summary>
        internal static string Config_SMTP_Success_Description {
            get {
                return ResourceManager.GetString("Config_SMTP_Success_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Settings Saved!.
        /// </summary>
        internal static string Config_SMTP_Success_Title {
            get {
                return ResourceManager.GetString("Config_SMTP_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;You must enter a valid e-mail address..
        /// </summary>
        internal static string Config_SMTP_Test_InValid {
            get {
                return ResourceManager.GetString("Config_SMTP_Test_InValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;You must enter an e-mail address to use for testing..
        /// </summary>
        internal static string Config_SMTP_Test_Required {
            get {
                return ResourceManager.GetString("Config_SMTP_Test_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test E-Mail:.
        /// </summary>
        internal static string Config_SMTP_Test_Title {
            get {
                return ResourceManager.GetString("Config_SMTP_Test_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;You must enter a username for the SMTP service to use..
        /// </summary>
        internal static string Config_SMTP_User_Required {
            get {
                return ResourceManager.GetString("Config_SMTP_User_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Config_SMTP_User_Title {
            get {
                return ResourceManager.GetString("Config_SMTP_User_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string Config_Users_Add {
            get {
                return ResourceManager.GetString("Config_Users_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Roles:.
        /// </summary>
        internal static string Config_Users_AssignRoles {
            get {
                return ResourceManager.GetString("Config_Users_AssignRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of users below has been granted access to the Administrative Portal of
        ///        uManage. From here you can add and remove users from the list below. In addition
        ///        you can also change user&apos;s group memberships from this panel as well.
        ///        &lt;p&gt;
        ///            &lt;strong&gt;Role Definitions&lt;/strong&gt;
        ///            &lt;br /&gt;
        ///            Admin - This is the primary role intended for users to manage the domain and the
        ///            users within it.
        ///            &lt;br /&gt;
        ///            System - This is the syste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config_Users_Body {
            get {
                return ResourceManager.GetString("Config_Users_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Users.
        /// </summary>
        internal static string Config_Users_CurrentUsers {
            get {
                return ResourceManager.GetString("Config_Users_CurrentUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Username:.
        /// </summary>
        internal static string Config_Users_EnterUsername {
            get {
                return ResourceManager.GetString("Config_Users_EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Users.
        /// </summary>
        internal static string Config_Users_NewUsers {
            get {
                return ResourceManager.GetString("Config_Users_NewUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a User....
        /// </summary>
        internal static string Config_Users_SelectUser {
            get {
                return ResourceManager.GetString("Config_Users_SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select User:.
        /// </summary>
        internal static string Config_Users_SelectUsername {
            get {
                return ResourceManager.GetString("Config_Users_SelectUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Roles.
        /// </summary>
        internal static string Config_Users_Update {
            get {
                return ResourceManager.GetString("Config_Users_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Roles:.
        /// </summary>
        internal static string Config_Users_UserRoles {
            get {
                return ResourceManager.GetString("Config_Users_UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An administrator has either disabled adding employees using this system or has not yet configured the system to add new employees.  Please contact your administrator for more information..
        /// </summary>
        internal static string Emp_Add_Disabled_Message {
            get {
                return ResourceManager.GetString("Emp_Add_Disabled_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee Disabled!.
        /// </summary>
        internal static string Emp_Add_Disabled_Title {
            get {
                return ResourceManager.GetString("Emp_Add_Disabled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        internal static string Emp_Add_Submit {
            get {
                return ResourceManager.GetString("Emp_Add_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee could not be added to the system because: {0}.
        /// </summary>
        internal static string Emp_Add_Submit_Fail_Msg {
            get {
                return ResourceManager.GetString("Emp_Add_Submit_Fail_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add Employee!.
        /// </summary>
        internal static string Emp_Add_Submit_Fail_Title {
            get {
                return ResourceManager.GetString("Emp_Add_Submit_Fail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee was added to the system.  The system will send you an e-mail in a few minutes with instructions and login information for the new employee, please deliver it to the new employee..
        /// </summary>
        internal static string Emp_Add_Submit_Success_Msg {
            get {
                return ResourceManager.GetString("Emp_Add_Submit_Success_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Added!.
        /// </summary>
        internal static string Emp_Add_Submit_Success_Title {
            get {
                return ResourceManager.GetString("Emp_Add_Submit_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string Emp_Details_Info {
            get {
                return ResourceManager.GetString("Emp_Details_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Information.
        /// </summary>
        internal static string Emp_Details_Location {
            get {
                return ResourceManager.GetString("Emp_Details_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Manager.
        /// </summary>
        internal static string Emp_Details_NoManager {
            get {
                return ResourceManager.GetString("Emp_Details_NoManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Information.
        /// </summary>
        internal static string Emp_Details_Org {
            get {
                return ResourceManager.GetString("Emp_Details_Org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Information.
        /// </summary>
        internal static string Emp_Details_Phone {
            get {
                return ResourceManager.GetString("Emp_Details_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Settings.
        /// </summary>
        internal static string Emp_Details_Photo {
            get {
                return ResourceManager.GetString("Emp_Details_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some reason the system was not able to change the photo submitted or clear the existing photo.  Try again or contact an administrator for more assistance.  Here is the exact reason: {0}..
        /// </summary>
        internal static string Emp_Details_Photo_Fail_Msg {
            get {
                return ResourceManager.GetString("Emp_Details_Photo_Fail_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Update Photo!.
        /// </summary>
        internal static string Emp_Details_Photo_Fail_Title {
            get {
                return ResourceManager.GetString("Emp_Details_Photo_Fail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system was unable to to save the information.  Here is the exact reason: {0}..
        /// </summary>
        internal static string Emp_Details_Save_Fail_Msg {
            get {
                return ResourceManager.GetString("Emp_Details_Save_Fail_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Update Information!.
        /// </summary>
        internal static string Emp_Details_Save_Fail_Title {
            get {
                return ResourceManager.GetString("Emp_Details_Save_Fail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information for the employee has been saved.  It should take effect immediately, however some applications may need to be restarted to get the new changes..
        /// </summary>
        internal static string Emp_Details_Save_Success_Msg {
            get {
                return ResourceManager.GetString("Emp_Details_Save_Success_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Updated!.
        /// </summary>
        internal static string Emp_Details_Save_Success_Title {
            get {
                return ResourceManager.GetString("Emp_Details_Save_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        internal static string Emp_List_Details {
            get {
                return ResourceManager.GetString("Emp_List_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string Emp_List_Email {
            get {
                return ResourceManager.GetString("Emp_List_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        internal static string Emp_List_ID {
            get {
                return ResourceManager.GetString("Emp_List_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Emp_List_Name {
            get {
                return ResourceManager.GetString("Emp_List_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Emp_List_Status {
            get {
                return ResourceManager.GetString("Emp_List_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Emp_List_Title {
            get {
                return ResourceManager.GetString("Emp_List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Lymphoma Awareness.
        /// </summary>
        internal static string Foot_Lymphoma {
            get {
                return ResourceManager.GetString("Foot_Lymphoma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make A Suggestion.
        /// </summary>
        internal static string Foot_MakeSuggestion {
            get {
                return ResourceManager.GetString("Foot_MakeSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uManage Version &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        internal static string Foot_Version {
            get {
                return ResourceManager.GetString("Foot_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        internal static string Mast_Username {
            get {
                return ResourceManager.GetString("Mast_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to User Portal.
        /// </summary>
        internal static string Mast_ViewUserPortal {
            get {
                return ResourceManager.GetString("Mast_ViewUserPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new employee to your organization.
        /// </summary>
        internal static string Menu_Admin_AddUser_Description {
            get {
                return ResourceManager.GetString("Menu_Admin_AddUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Employee.
        /// </summary>
        internal static string Menu_Admin_AddUser_Title {
            get {
                return ResourceManager.GetString("Menu_Admin_AddUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        internal static string Menu_Admin_AddUser_Title_Short {
            get {
                return ResourceManager.GetString("Menu_Admin_AddUser_Title_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View an overview of the current users and system history.
        /// </summary>
        internal static string Menu_Admin_Dash_Description {
            get {
                return ResourceManager.GetString("Menu_Admin_Dash_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration Dashboard.
        /// </summary>
        internal static string Menu_Admin_Dash_Title {
            get {
                return ResourceManager.GetString("Menu_Admin_Dash_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Menu_Admin_Dash_Title_Short {
            get {
                return ResourceManager.GetString("Menu_Admin_Dash_Title_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and manage employees.
        /// </summary>
        internal static string Menu_Admin_UserList_Description {
            get {
                return ResourceManager.GetString("Menu_Admin_UserList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Employee List.
        /// </summary>
        internal static string Menu_Admin_UserList_Title {
            get {
                return ResourceManager.GetString("Menu_Admin_UserList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string Menu_Admin_UserList_Title_Short {
            get {
                return ResourceManager.GetString("Menu_Admin_UserList_Title_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and manage the details and settings for an employee.
        /// </summary>
        internal static string Menu_Admin_UserManage_Description {
            get {
                return ResourceManager.GetString("Menu_Admin_UserManage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Employee Information.
        /// </summary>
        internal static string Menu_Admin_UserManage_Title {
            get {
                return ResourceManager.GetString("Menu_Admin_UserManage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Employee.
        /// </summary>
        internal static string Menu_Admin_UserManage_Title_Short {
            get {
                return ResourceManager.GetString("Menu_Admin_UserManage_Title_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the application to the defaults.
        /// </summary>
        internal static string Menu_Config_AppReset_Description {
            get {
                return ResourceManager.GetString("Menu_Config_AppReset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Reset.
        /// </summary>
        internal static string Menu_Config_AppReset_Title {
            get {
                return ResourceManager.GetString("Menu_Config_AppReset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View an overview of current configuration tasks.
        /// </summary>
        internal static string Menu_Config_Dash_Description {
            get {
                return ResourceManager.GetString("Menu_Config_Dash_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Timeline.
        /// </summary>
        internal static string Menu_Config_Dash_Title {
            get {
                return ResourceManager.GetString("Menu_Config_Dash_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Menu_Config_Dash_Title_Short {
            get {
                return ResourceManager.GetString("Menu_Config_Dash_Title_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and modify the current database configuration.
        /// </summary>
        internal static string Menu_Config_Database_Description {
            get {
                return ResourceManager.GetString("Menu_Config_Database_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Configuration.
        /// </summary>
        internal static string Menu_Config_Database_Title {
            get {
                return ResourceManager.GetString("Menu_Config_Database_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and modify the current domain connection and configuration.
        /// </summary>
        internal static string Menu_Config_Domain_Description {
            get {
                return ResourceManager.GetString("Menu_Config_Domain_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Configuration.
        /// </summary>
        internal static string Menu_Config_Domain_Title {
            get {
                return ResourceManager.GetString("Menu_Config_Domain_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the default settings for new users that are added through uManage.
        /// </summary>
        internal static string Menu_Config_NewUser_Description {
            get {
                return ResourceManager.GetString("Menu_Config_NewUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Defaults.
        /// </summary>
        internal static string Menu_Config_NewUser_Title {
            get {
                return ResourceManager.GetString("Menu_Config_NewUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the Office Locations for the User Portal.
        /// </summary>
        internal static string Menu_Config_OfficeLoc_Description {
            get {
                return ResourceManager.GetString("Menu_Config_OfficeLoc_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Location Configuration.
        /// </summary>
        internal static string Menu_Config_OfficeLoc_Title {
            get {
                return ResourceManager.GetString("Menu_Config_OfficeLoc_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and modify user portal configuration.
        /// </summary>
        internal static string Menu_Config_Portal_Description {
            get {
                return ResourceManager.GetString("Menu_Config_Portal_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Portal Configuration.
        /// </summary>
        internal static string Menu_Config_Portal_Title {
            get {
                return ResourceManager.GetString("Menu_Config_Portal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and modify the current SMTP Server configuration.
        /// </summary>
        internal static string Menu_Config_SMTP_Description {
            get {
                return ResourceManager.GetString("Menu_Config_SMTP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Configuration.
        /// </summary>
        internal static string Menu_Config_SMTP_Title {
            get {
                return ResourceManager.GetString("Menu_Config_SMTP_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable and configure Microsoft Tag.
        /// </summary>
        internal static string Menu_Config_Tag_Description {
            get {
                return ResourceManager.GetString("Menu_Config_Tag_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Tag Configuration.
        /// </summary>
        internal static string Menu_Config_Tag_Title {
            get {
                return ResourceManager.GetString("Menu_Config_Tag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the complete system timeline.
        /// </summary>
        internal static string Menu_Config_Timeline_Description {
            get {
                return ResourceManager.GetString("Menu_Config_Timeline_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Timeline (Full).
        /// </summary>
        internal static string Menu_Config_Timeline_Title {
            get {
                return ResourceManager.GetString("Menu_Config_Timeline_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and Modify the users that are allowed to access the Admin Portal of uManage.
        /// </summary>
        internal static string Menu_Config_Users_Description {
            get {
                return ResourceManager.GetString("Menu_Config_Users_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Admin Users.
        /// </summary>
        internal static string Menu_Config_Users_Title {
            get {
                return ResourceManager.GetString("Menu_Config_Users_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Full Timeline.
        /// </summary>
        internal static string Menu_Sidebar_FullTimeline {
            get {
                return ResourceManager.GetString("Menu_Sidebar_FullTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline Tasks.
        /// </summary>
        internal static string Menu_Sidebar_TimelineTasks {
            get {
                return ResourceManager.GetString("Menu_Sidebar_TimelineTasks", resourceCulture);
            }
        }
    }
}
