//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;copy; 2010 Pabst Productions, Inc. - All Rights Reserved.
        /// </summary>
        internal static string CopyrightTag {
            get {
                return ResourceManager.GetString("CopyrightTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Licensed under the &lt;strong&gt;&lt;a href=&quot;http://www.opensource.org/licenses/ms-pl.html&quot; target=&quot;_blank&quot;&gt;Microsoft Public License&lt;/a&gt;&lt;/strong&gt;.
        /// </summary>
        internal static string OpenSourceTag {
            get {
                return ResourceManager.GetString("OpenSourceTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                                uManage is free and open source software. As with most open-source software projects
        ///                                donations are always accepted to assist with the cost of working on the project
        ///                                and maintaining the application. However, we prefer that any donations should go
        ///                                to good use rather than our pockets. If you like the software or are simply looking
        ///                                for a good ca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RibbonBody {
            get {
                return ResourceManager.GetString("RibbonBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Lymphoma Awareness.
        /// </summary>
        internal static string RibbonTitle {
            get {
                return ResourceManager.GetString("RibbonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Ago.
        /// </summary>
        internal static string Time_HoursAgo {
            get {
                return ResourceManager.GetString("Time_HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes Ago.
        /// </summary>
        internal static string Time_MinutesAgo {
            get {
                return ResourceManager.GetString("Time_MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds Ago.
        /// </summary>
        internal static string Time_SecondsAgo {
            get {
                return ResourceManager.GetString("Time_SecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Less.
        /// </summary>
        internal static string ViewLess {
            get {
                return ResourceManager.GetString("ViewLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
