//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Setup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Setup", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Name:.
        /// </summary>
        internal static string Setup_ADConfigure_Domain {
            get {
                return ResourceManager.GetString("Setup_ADConfigure_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Setup_ADConfigure_Password {
            get {
                return ResourceManager.GetString("Setup_ADConfigure_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you click next uManage will attempt to connect and test the connection to the domain.  This test ensures you have the proper permissions to access the domain and modify user settings..
        /// </summary>
        internal static string Setup_ADConfigure_TestPrompt {
            get {
                return ResourceManager.GetString("Setup_ADConfigure_TestPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure and Test AD Connection.
        /// </summary>
        internal static string Setup_ADConfigure_Title {
            get {
                return ResourceManager.GetString("Setup_ADConfigure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Setup_ADConfigure_Username {
            get {
                return ResourceManager.GetString("Setup_ADConfigure_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Password:.
        /// </summary>
        internal static string Setup_ADConfigure_VerifyPassword {
            get {
                return ResourceManager.GetString("Setup_ADConfigure_VerifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Configure the Database?.
        /// </summary>
        internal static string Setup_Database_AutoConfigure {
            get {
                return ResourceManager.GetString("Setup_Database_AutoConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to the database server will be verified when you click next, the
        ///                                    database will not be created until the end of the wizard..
        /// </summary>
        internal static string Setup_Database_Footer {
            get {
                return ResourceManager.GetString("Setup_Database_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to simplify the database installation process as much as possible this
        ///                                    setup wizard is capable of connecting to your server, creating the database and
        ///                                    creating a secure user account to run under. However it is understood that in some
        ///                                    cases you may already have a database setup or would like to setup the database
        ///                                    yourself. To allow uManage to setup the d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Setup_Database_Message {
            get {
                return ResourceManager.GetString("Setup_Database_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA Password:.
        /// </summary>
        internal static string Setup_Database_Password {
            get {
                return ResourceManager.GetString("Setup_Database_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address:.
        /// </summary>
        internal static string Setup_Database_Server {
            get {
                return ResourceManager.GetString("Setup_Database_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Configuration.
        /// </summary>
        internal static string Setup_Database_Title {
            get {
                return ResourceManager.GetString("Setup_Database_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain User:.
        /// </summary>
        internal static string Setup_Database_UserAccount {
            get {
                return ResourceManager.GetString("Setup_Database_UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account specified was invalid or could not be found in the directory.  Please select a different user account..
        /// </summary>
        internal static string Setup_Error_AdUser_Message {
            get {
                return ResourceManager.GetString("Setup_Error_AdUser_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Invalid!.
        /// </summary>
        internal static string Setup_Error_AdUser_Title {
            get {
                return ResourceManager.GetString("Setup_Error_AdUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uManage was unable to either connect to the database server or validate the SA credentials specified are allowed to perform the required actions.  Verify the server is online and available and that you specified the correct credentials..
        /// </summary>
        internal static string Setup_Error_Database_Message {
            get {
                return ResourceManager.GetString("Setup_Error_Database_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Connect to the Database Server.
        /// </summary>
        internal static string Setup_Error_Database_Title {
            get {
                return ResourceManager.GetString("Setup_Error_Database_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uManage was unable to either connect to the domain or validate that the user credentials specified are allowed to perform all required actions.  Verify your domain is available and ensure the user being used has the proper permissions..
        /// </summary>
        internal static string Setup_Error_Domain_Message {
            get {
                return ResourceManager.GetString("Setup_Error_Domain_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Connect to the Domain.
        /// </summary>
        internal static string Setup_Error_Domain_Title {
            get {
                return ResourceManager.GetString("Setup_Error_Domain_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license file could not be read.  uManage is supposed to have a license file in the root web directory otherwise it will not configure itself properly.  Don&apos;t try to steal this software!.
        /// </summary>
        internal static string Setup_Error_License {
            get {
                return ResourceManager.GetString("Setup_Error_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;The password verification did not match the original password.  Please ensure both password&apos;s match..
        /// </summary>
        internal static string Setup_Invalid_ComparePassword {
            get {
                return ResourceManager.GetString("Setup_Invalid_ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;You must enter a database server to connect to..
        /// </summary>
        internal static string Setup_Invalid_DbServer {
            get {
                return ResourceManager.GetString("Setup_Invalid_DbServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;You must enter a domain name to connect to..
        /// </summary>
        internal static string Setup_Invalid_Domain {
            get {
                return ResourceManager.GetString("Setup_Invalid_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;You must enter a password..
        /// </summary>
        internal static string Setup_Invalid_Password {
            get {
                return ResourceManager.GetString("Setup_Invalid_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;You must enter a domain user account to add to uManage..
        /// </summary>
        internal static string Setup_Invalid_UserAccount {
            get {
                return ResourceManager.GetString("Setup_Invalid_UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;You must enter a username for the account with permission to modify the domain..
        /// </summary>
        internal static string Setup_Invalid_Username {
            get {
                return ResourceManager.GetString("Setup_Invalid_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking next you agree to abide by the license..
        /// </summary>
        internal static string Setup_LicenseAgreement {
            get {
                return ResourceManager.GetString("Setup_LicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///&lt;strong&gt;License Agreement&lt;/strong&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///uManage is license under the Microsoft Public License or Ms-PL. You must agree to
        ///the license before you may use or redistribute the software. If you redistribute
        ///the software the license file must always accompany the software.
        ///&lt;/p&gt;.
        /// </summary>
        internal static string Setup_LicenseMessage {
            get {
                return ResourceManager.GetString("Setup_LicenseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to modify any of their attributes (Overrides options below).
        /// </summary>
        internal static string Setup_PortalSettings_AllowChanges {
            get {
                return ResourceManager.GetString("Setup_PortalSettings_AllowChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to modify e-mail address.
        /// </summary>
        internal static string Setup_PortalSettings_AllowEmail {
            get {
                return ResourceManager.GetString("Setup_PortalSettings_AllowEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to modify location information.
        /// </summary>
        internal static string Setup_PortalSettings_AllowLocation {
            get {
                return ResourceManager.GetString("Setup_PortalSettings_AllowLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to modify their name.
        /// </summary>
        internal static string Setup_PortalSettings_AllowName {
            get {
                return ResourceManager.GetString("Setup_PortalSettings_AllowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow users to change password.
        /// </summary>
        internal static string Setup_PortalSettings_AllowPassChange {
            get {
                return ResourceManager.GetString("Setup_PortalSettings_AllowPassChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user to modify phone numbers.
        /// </summary>
        internal static string Setup_PortalSettings_AllowPhone {
            get {
                return ResourceManager.GetString("Setup_PortalSettings_AllowPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow users to change photos.
        /// </summary>
        internal static string Setup_PortalSettings_AllowPhoto {
            get {
                return ResourceManager.GetString("Setup_PortalSettings_AllowPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display user location information.
        /// </summary>
        internal static string Setup_PortalSettings_DisplayLocation {
            get {
                return ResourceManager.GetString("Setup_PortalSettings_DisplayLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display user account notes.
        /// </summary>
        internal static string Setup_PortalSettings_DisplayNotes {
            get {
                return ResourceManager.GetString("Setup_PortalSettings_DisplayNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display user organization section.
        /// </summary>
        internal static string Setup_PortalSettings_DisplayOrg {
            get {
                return ResourceManager.GetString("Setup_PortalSettings_DisplayOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display user phone numbers.
        /// </summary>
        internal static string Setup_PortalSettings_DisplayPhone {
            get {
                return ResourceManager.GetString("Setup_PortalSettings_DisplayPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display user photo section.
        /// </summary>
        internal static string Setup_PortalSettings_DisplayPhoto {
            get {
                return ResourceManager.GetString("Setup_PortalSettings_DisplayPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select settings that affect what typical users can see and/or change when they use the self-service portal..
        /// </summary>
        internal static string Setup_PortalSettings_Title {
            get {
                return ResourceManager.GetString("Setup_PortalSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///&lt;strong&gt;How Setup Works&lt;/strong&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///In order to get uManage running this setup wizard will do the following:
        ///&lt;/p&gt;
        ///&lt;ol&gt;
        ///&lt;li&gt;&lt;s&gt;Tell you about the application&lt;/s&gt; - Done!&lt;/li&gt;
        ///&lt;li&gt;&lt;s&gt;Tell you what we need to configure&lt;/s&gt; - Done!&lt;/li&gt;
        ///&lt;li&gt;Accept the license agreement&lt;/li&gt;
        ///&lt;li&gt;Connect to your domain&lt;/li&gt;
        ///&lt;li&gt;Create a database&lt;/li&gt;
        ///&lt;li&gt;Setup an admin user&lt;/li&gt;
        ///&lt;li&gt;Select the Self-Service Portal settings&lt;/li&gt;
        ///&lt;li&gt;Use uManage!&lt;/li&gt;
        ///&lt;/ol&gt;.
        /// </summary>
        internal static string Setup_ProcessMessage {
            get {
                return ResourceManager.GetString("Setup_ProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Database Name: &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        internal static string Setup_Summary_DbCatalog {
            get {
                return ResourceManager.GetString("Setup_Summary_DbCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;You have decided not to let uManage setup the database.  uManage will be offline until you configure the database.&lt;/strong&gt;.
        /// </summary>
        internal static string Setup_Summary_DbNotEnabled {
            get {
                return ResourceManager.GetString("Setup_Summary_DbNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Server: &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        internal static string Setup_Summary_DbServer {
            get {
                return ResourceManager.GetString("Setup_Summary_DbServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting as: &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        internal static string Setup_Summary_DbUser {
            get {
                return ResourceManager.GetString("Setup_Summary_DbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using: &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        internal static string Setup_Summary_Domain {
            get {
                return ResourceManager.GetString("Setup_Summary_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified Access from: &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        internal static string Setup_Summary_DomainController {
            get {
                return ResourceManager.GetString("Setup_Summary_DomainController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you click next the system will configure the application with the options above, recycle the application, disable the setup wizard and redirect you to the user portal.  This could take a minute to complete..
        /// </summary>
        internal static string Setup_Summary_Prompt {
            get {
                return ResourceManager.GetString("Setup_Summary_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uManage has already confirmed a successful connection to the domain, however you should still confirm the selections below and make any last minute changes before you click finish. Once you click finish the system will be configured and you will no longer be able to access this wizard..
        /// </summary>
        internal static string Setup_Summary_Title {
            get {
                return ResourceManager.GetString("Setup_Summary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting as: &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        internal static string Setup_Summary_Username {
            get {
                return ResourceManager.GetString("Setup_Summary_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uManage Setup Wizard.
        /// </summary>
        internal static string Setup_Title {
            get {
                return ResourceManager.GetString("Setup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///&lt;strong&gt;Welcome to uManage!&lt;/strong&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///uManage is a web application designed to assist organizations with helping to handle
        ///much of the user load generated by simple tasks like creating users as well as managing
        ///user information in Microsoft’s Active Directory system. It allows for other departments
        ///in an organization like Human Resources to take an active part in streamlining the
        ///new hire and termination process for any organization while freeing IT resources
        ///for more intensive or impor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Setup_WelcomeMessage {
            get {
                return ResourceManager.GetString("Setup_WelcomeMessage", resourceCulture);
            }
        }
    }
}
