//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.User", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string Info_Address1_Header {
            get {
                return ResourceManager.GetString("Info_Address1_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Box, Apt, Ste:.
        /// </summary>
        internal static string Info_Address2_Header {
            get {
                return ResourceManager.GetString("Info_Address2_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return confirm(&apos;Some programs that rely on information from your profile may malfunction or stop working once your information is updated.  You may need to restart some programs after making any changes. \r\n\r\nAre you sure you want to update your information?&apos;);.
        /// </summary>
        internal static string Info_Change_Alert_Code {
            get {
                return ResourceManager.GetString("Info_Change_Alert_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information could not be updated.  Please try again or contact a systems administrator for more information.  The details were:&lt;p&gt;&lt;span class=&quot;errortext&quot;&gt;{0}&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        internal static string Info_Change_Failure_Message {
            get {
                return ResourceManager.GetString("Info_Change_Failure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Update Information!.
        /// </summary>
        internal static string Info_Change_Failure_Title {
            get {
                return ResourceManager.GetString("Info_Change_Failure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;The email address entered is not in the correct format. (you@yourcompany.com).
        /// </summary>
        internal static string Info_Change_Invalid_Email {
            get {
                return ResourceManager.GetString("Info_Change_Invalid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter valid entries for all of the fields in order to update your information..
        /// </summary>
        internal static string Info_Change_Invalid_FieldsMissing {
            get {
                return ResourceManager.GetString("Info_Change_Invalid_FieldsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;The name entered either does not exist or is invalid.  You must specify a name..
        /// </summary>
        internal static string Info_Change_Invalid_Name {
            get {
                return ResourceManager.GetString("Info_Change_Invalid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Fields Missing!.
        /// </summary>
        internal static string Info_Change_Invalid_Title {
            get {
                return ResourceManager.GetString("Info_Change_Invalid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;The website URL entered is not in the correct format. (http://www.yourcompany.com).
        /// </summary>
        internal static string Info_Change_Invalid_URL {
            get {
                return ResourceManager.GetString("Info_Change_Invalid_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uManage was unable to upload your photo and save it to the directory.  There could have been a problem with your photo or with the system.  Try uploading a different photo, if it still fails there is probably something wrong with the application or the network..
        /// </summary>
        internal static string Info_Change_Photo_Failure_Message {
            get {
                return ResourceManager.GetString("Info_Change_Photo_Failure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Upload Photo.
        /// </summary>
        internal static string Info_Change_Photo_Failure_Title {
            get {
                return ResourceManager.GetString("Info_Change_Photo_Failure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only JPEG, BMP, GIF and PNG files are supported image formats to upload.  Please select a different file and try again..
        /// </summary>
        internal static string Info_Change_Photo_Invalid_Ext {
            get {
                return ResourceManager.GetString("Info_Change_Photo_Invalid_Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Information.
        /// </summary>
        internal static string Info_Change_Submit {
            get {
                return ResourceManager.GetString("Info_Change_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information was updated successfully.  All changes take effect almost immediately, however any open application may need to be restarted to get your new information..
        /// </summary>
        internal static string Info_Change_Success_Message {
            get {
                return ResourceManager.GetString("Info_Change_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Updated!.
        /// </summary>
        internal static string Info_Change_Success_Title {
            get {
                return ResourceManager.GetString("Info_Change_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string Info_City_Header {
            get {
                return ResourceManager.GetString("Info_City_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company:.
        /// </summary>
        internal static string Info_Company_Header {
            get {
                return ResourceManager.GetString("Info_Company_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string Info_Country_Header {
            get {
                return ResourceManager.GetString("Info_Country_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department:.
        /// </summary>
        internal static string Info_Department_Header {
            get {
                return ResourceManager.GetString("Info_Department_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your systems administrator has chosen to not allow any changes to your information.  You are more than welcome to review your information but an administrator will have to make any changes for you..
        /// </summary>
        internal static string Info_Disabled_Message {
            get {
                return ResourceManager.GetString("Info_Disabled_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifications Disabled!.
        /// </summary>
        internal static string Info_Disabled_Title {
            get {
                return ResourceManager.GetString("Info_Disabled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Address:.
        /// </summary>
        internal static string Info_Email_Header {
            get {
                return ResourceManager.GetString("Info_Email_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID:.
        /// </summary>
        internal static string Info_EmployeeId_Header {
            get {
                return ResourceManager.GetString("Info_EmployeeId_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax:.
        /// </summary>
        internal static string Info_FaxPhone_Header {
            get {
                return ResourceManager.GetString("Info_FaxPhone_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        internal static string Info_FirstName_Header {
            get {
                return ResourceManager.GetString("Info_FirstName_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone:.
        /// </summary>
        internal static string Info_HomePhone_Header {
            get {
                return ResourceManager.GetString("Info_HomePhone_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIP/Skype:.
        /// </summary>
        internal static string Info_IPPhone_Header {
            get {
                return ResourceManager.GetString("Info_IPPhone_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        internal static string Info_LastName_Header {
            get {
                return ResourceManager.GetString("Info_LastName_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager:.
        /// </summary>
        internal static string Info_Manager_Header {
            get {
                return ResourceManager.GetString("Info_Manager_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name:.
        /// </summary>
        internal static string Info_MiddleName_Header {
            get {
                return ResourceManager.GetString("Info_MiddleName_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone:.
        /// </summary>
        internal static string Info_MobilePhone_Header {
            get {
                return ResourceManager.GetString("Info_MobilePhone_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Information.
        /// </summary>
        internal static string Info_MyInfo_Title {
            get {
                return ResourceManager.GetString("Info_MyInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Location.
        /// </summary>
        internal static string Info_MyLoc_Title {
            get {
                return ResourceManager.GetString("Info_MyLoc_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Organization.
        /// </summary>
        internal static string Info_MyOrg_Title {
            get {
                return ResourceManager.GetString("Info_MyOrg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Phone Numbers.
        /// </summary>
        internal static string Info_MyPhone_Title {
            get {
                return ResourceManager.GetString("Info_MyPhone_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Phone:.
        /// </summary>
        internal static string Info_OfficePhone_Header {
            get {
                return ResourceManager.GetString("Info_OfficePhone_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office:.
        /// </summary>
        internal static string Info_Office_Header {
            get {
                return ResourceManager.GetString("Info_Office_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization information can never be modified.  If you find something you beleive is incorrect please contact an administrator..
        /// </summary>
        internal static string Info_Org_Info_Message {
            get {
                return ResourceManager.GetString("Info_Org_Info_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Information Cannot Be Modified!.
        /// </summary>
        internal static string Info_Org_Info_Title {
            get {
                return ResourceManager.GetString("Info_Org_Info_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pager/SMS:.
        /// </summary>
        internal static string Info_PagerPhone_Header {
            get {
                return ResourceManager.GetString("Info_PagerPhone_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear My Photo.
        /// </summary>
        internal static string Info_Photo_Clear_Header {
            get {
                return ResourceManager.GetString("Info_Photo_Clear_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Removes the Current Photo).
        /// </summary>
        internal static string Info_Photo_Clear_Text {
            get {
                return ResourceManager.GetString("Info_Photo_Clear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Photo:.
        /// </summary>
        internal static string Info_Photo_Current_Header {
            get {
                return ResourceManager.GetString("Info_Photo_Current_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Formats: JPEG, BMP, PNG, GIF.
        /// </summary>
        internal static string Info_Photo_New_Extensions {
            get {
                return ResourceManager.GetString("Info_Photo_New_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select New Photo:.
        /// </summary>
        internal static string Info_Photo_New_Header {
            get {
                return ResourceManager.GetString("Info_Photo_New_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Picture.
        /// </summary>
        internal static string Info_Photo_Title {
            get {
                return ResourceManager.GetString("Info_Photo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        internal static string Info_Position_Header {
            get {
                return ResourceManager.GetString("Info_Position_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        internal static string Info_State_Header {
            get {
                return ResourceManager.GetString("Info_State_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back {0}!.
        /// </summary>
        internal static string Info_SubTitle_Text {
            get {
                return ResourceManager.GetString("Info_SubTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website:.
        /// </summary>
        internal static string Info_Website_Header {
            get {
                return ResourceManager.GetString("Info_Website_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code:.
        /// </summary>
        internal static string Info_ZipCode_Header {
            get {
                return ResourceManager.GetString("Info_ZipCode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        internal static string Mast_UserName {
            get {
                return ResourceManager.GetString("Mast_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Admin Portal.
        /// </summary>
        internal static string Mast_ViewAdminPortal {
            get {
                return ResourceManager.GetString("Mast_ViewAdminPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        internal static string Menu_AboutMe_Title {
            get {
                return ResourceManager.GetString("Menu_AboutMe_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        internal static string Menu_MyAccount_Title {
            get {
                return ResourceManager.GetString("Menu_MyAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Password.
        /// </summary>
        internal static string Menu_MyPassword_Title {
            get {
                return ResourceManager.GetString("Menu_MyPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Expiration Date:.
        /// </summary>
        internal static string MyAccount_AccountExp_Header {
            get {
                return ResourceManager.GetString("MyAccount_AccountExp_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Locked:.
        /// </summary>
        internal static string MyAccount_AccountLocked_Header {
            get {
                return ResourceManager.GetString("MyAccount_AccountLocked_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes/Comments:.
        /// </summary>
        internal static string MyAccount_Notes_Header {
            get {
                return ResourceManager.GetString("MyAccount_Notes_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Expiration Date:.
        /// </summary>
        internal static string MyAccount_PasswordExp_Header {
            get {
                return ResourceManager.GetString("MyAccount_PasswordExp_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, here are the details of your account:.
        /// </summary>
        internal static string MyAccount_SubTitle_Text {
            get {
                return ResourceManager.GetString("MyAccount_SubTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Username:.
        /// </summary>
        internal static string MyAccount_Username_Header {
            get {
                return ResourceManager.GetString("MyAccount_Username_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm(&apos;While your password is being changed other applications could stop functioning or working properly.  You may have to restart some programs.\r\n\r\nAre you sure you want to change your password?&apos;);.
        /// </summary>
        internal static string Password_Change_Alert_Code {
            get {
                return ResourceManager.GetString("Password_Change_Alert_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, it appears a system administrator has chosen to not let you change your password using uManage.  Please contact your administrator for more assistance in changing your password..
        /// </summary>
        internal static string Password_Change_Disabled_Message {
            get {
                return ResourceManager.GetString("Password_Change_Disabled_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Change Disabled!.
        /// </summary>
        internal static string Password_Change_Disabled_Title {
            get {
                return ResourceManager.GetString("Password_Change_Disabled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password could not be updated.  Please try again or contact a systems administrator for more information..
        /// </summary>
        internal static string Password_Change_Error_Message {
            get {
                return ResourceManager.GetString("Password_Change_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Change Failure!.
        /// </summary>
        internal static string Password_Change_Error_Title {
            get {
                return ResourceManager.GetString("Password_Change_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;The new password and the confirmation password do not match, please try again..
        /// </summary>
        internal static string Password_Change_Invalid_Confirm {
            get {
                return ResourceManager.GetString("Password_Change_Invalid_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Invalid Entry!&lt;/strong&gt;&lt;br /&gt;The field is either empty or invalid, you must specify a password..
        /// </summary>
        internal static string Password_Change_Invalid_Password {
            get {
                return ResourceManager.GetString("Password_Change_Invalid_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string Password_Change_Submit_Text {
            get {
                return ResourceManager.GetString("Password_Change_Submit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was updated successfully.  It takes effect almost immediately, you may have to log-out and log-in for some applications to continue working..
        /// </summary>
        internal static string Password_Change_Success_Message {
            get {
                return ResourceManager.GetString("Password_Change_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Change Success!.
        /// </summary>
        internal static string Password_Change_Success_Title {
            get {
                return ResourceManager.GetString("Password_Change_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password:.
        /// </summary>
        internal static string Password_ConfPass_Title {
            get {
                return ResourceManager.GetString("Password_ConfPass_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password:.
        /// </summary>
        internal static string Password_NewPass_Title {
            get {
                return ResourceManager.GetString("Password_NewPass_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password:.
        /// </summary>
        internal static string Password_OldPass_Title {
            get {
                return ResourceManager.GetString("Password_OldPass_Title", resourceCulture);
            }
        }
    }
}
